server:
  port: 80
  error:
    include-message: always
spring:
  datasource:
    username: 'postgres'
    password: '0706'
    url: 'jdbc:postgresql://localhost:5432/coding_bat'
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB